config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  mount ActionCable.server => '/cable'

  root to: 'homes#show'

  resource :workshop
  resource :server, only: [:show]
  resources :rooms, only: [:index, :show, :create]
  resources :messages, only: [:show, :create]
  resources :users, only: [:show]
  resource :client
  resource :fake_post, only: [:create]

end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController

  def show
    render "workshops/#{params[:page]}" if params[:page]
  end

end

app/views/workshops/_outline.html.erb
<ol>
  <h3><li>Developer tools</li></h3>
  <ul>
    <li><%= link_to 'Browser inspector', workshop_path(page: '1/1'), class: 'btn btn-lg index_link' %></li>
    <li><%= link_to 'Manipulate elements', workshop_path(page: '1/2'), class: 'btn btn-lg index_link' %></li>
    <li><%= link_to 'Browser console', workshop_path(page: '1/3'), class: 'btn btn-lg index_link' %></li>
    <li><%= link_to 'Network activity', workshop_path(page: '1/4'), class: 'btn btn-lg index_link' %></li>
    <li><%= link_to 'Text editor', workshop_path(page: '1/5'), class: 'btn btn-lg index_link' %></li>
  </ul>
  <h3><li>HTML/CSS</li></h3>
  <ul>
    <li><%= link_to 'HTML documents and tags', workshop_path(page: '2/1'), class: 'btn btn-lg index_link' %></li>
    <li><%= link_to 'Applying styling', workshop_path(page: '2/2'), class: 'btn btn-lg index_link' %></li>
    <li><%= link_to 'Selectors', workshop_path(page: '2/3'), class: 'btn btn-lg index_link' %></li>
    <li><%= link_to 'Organising styles', workshop_path(page: '2/4'), class: 'btn btn-lg index_link' %></li>
    <li><%= link_to 'CSS libraries', workshop_path(page: '2/5'), class: 'btn btn-lg index_link' %></li>
    <li><%= link_to 'Fonts and icons', workshop_path(page: '2/6'), class: 'btn btn-lg index_link' %></li>
  </ul>
  <h3><li>Javascript</li></h3>
  <ul>
    <li><%= link_to 'Programming', workshop_path(page: '3/1'), class: 'btn btn-lg index_link' %></li>
    <li><%= link_to 'Data types', workshop_path(page: '3/2'), class: 'btn btn-lg index_link' %></li>
    <li><%= link_to 'JS libraries', workshop_path(page: '3/3'), class: 'btn btn-lg index_link' %></li>
    <li><%= link_to 'jQuery', workshop_path(page: '3/4'), class: 'btn btn-lg index_link' %></li>
    <li><%= link_to 'AJAX', workshop_path(page: '3/5'), class: 'btn btn-lg index_link' %></li>
  </ul>
  <h3><li>Web</li></h3>
  <ul>
    <li><%= link_to 'Clients and servers', workshop_path(page: '4/1'), class: 'btn btn-lg index_link' %></li>
    <li><%= link_to 'HTTP and its methods', workshop_path(page: '4/2'), class: 'btn btn-lg index_link' %></li>
    <li><%= link_to 'URLs and requests', workshop_path(page: '4/3'), class: 'btn btn-lg index_link' %></li>
    <li><%= link_to 'Query parameters', workshop_path(page: '4/4'), class: 'btn btn-lg index_link' %></li>
    <li><%= link_to 'APIs and AJAX', workshop_path(page: '4/5'), class: 'btn btn-lg index_link' %></li>
  </ul>
  <h3><li>Application</li></h3>
  <ul>
    <li><%= link_to 'Build a js application', workshop_path(page: '5/1'), class: 'btn btn-lg index_link' %></li>
    <li><%= link_to 'Integrate an API', workshop_path(page: '5/2'), class: 'btn btn-lg index_link' %></li>
    <li><%= link_to 'Post and get data', workshop_path(page: '5/3'), class: 'btn btn-lg index_link' %></li>
    <li><%= link_to 'Executing page updates', workshop_path(page: '5/4'), class: 'btn btn-lg index_link' %></li>
  </ul>
</ol>
<p>
  <%= link_to icon_text('Start: Browser inspector', 'fa-arrow-right'), workshop_path(page: '1/1'), class: 'btn btn-info pull-right' %>
</p>

app/views/workshops/show.html.erb
<h2><%= icon_text('Workshop', 'fa-keyboard-o') %></h2>
<ol>
  <h3><li>Developer tools</li></h3>
  <ol>
    <li><%= index_link_to 'Browser inspector', '1/1' %></li>
    <li><%= index_link_to 'Manipulate elements', '1/2' %></li>
    <li><%= index_link_to 'Browser console', '1/3' %></li>
    <li><%= index_link_to 'Network activity', '1/4' %></li>
    <li><%= index_link_to 'Text editor', '1/5' %></li>
  </ol>
  <h3><li>HTML/CSS</li></h3>
  <ol>
    <li><%= index_link_to 'HTML documents', '2/1' %></li>
    <li><%= index_link_to 'Styling', '2/2' %></li>
    <li><%= index_link_to 'Style definitions', '2/3' %></li>
    <li><%= index_link_to 'Responsive styling', '2/4' %></li>
    <li><%= index_link_to 'CSS', '2/5' %></li>
    <li><%= index_link_to 'Placeholder data', '2/6' %></li>
    <li><%= index_link_to 'Images', '2/7' %></li>
    <li><%= index_link_to 'Fonts', '2/8' %></li>
    <li><%= index_link_to 'Icons', '2/9' %></li>
    <li><%= index_link_to 'Forms', '2/10' %></li>
  </ol>
  <h3><li>Javascript</li></h3>
  <ol>
    <li><%= index_link_to 'Variables', '3/1' %></li>
    <li><%= index_link_to 'Grammar', '3/2' %></li>
    <li><%= index_link_to 'Logic', '3/3' %></li>
    <li><%= index_link_to 'Data types', '3/4' %></li>
    <li><%= index_link_to 'Strings', '3/5' %></li>
    <li><%= index_link_to 'Arrays', '3/6' %></li>
    <li><%= index_link_to 'Functions', '3/7' %></li>
    <li><%= index_link_to 'Objects', '3/8' %></li>
    <li><%= index_link_to 'JSON', '3/9' %></li>
    <li><%= index_link_to 'Data structures', '3/10' %></li>
    <li><%= index_link_to 'Standard library', '3/11' %></li>
    <li><%= index_link_to 'DOM', '3/12' %></li>
  </ol>
  <h3><li>Bootstrap</li></h3>
  <ol>
    <li><%= index_link_to 'Get Bootstrap', '4/1' %></li>
    <li><%= index_link_to 'Apply styles', '4/2' %></li>
    <li><%= index_link_to 'Grid', '4/3' %></li>
  </ol>
  <h3><li>jQuery</li></h3>
  <ol>
    <li><%= index_link_to 'Get jQuery', '5/1' %></li>
    <li><%= index_link_to 'Test it', '5/2' %></li>
  </ol>
  <h3><li>Web</li></h3>
  <ol>
    <li><%= index_link_to 'Web requests', '5/1' %></li>
    <li><%= index_link_to 'Web resources', '5/2' %></li>
    <li><%= index_link_to 'Server', '5/3' %></li>
    <li><%= index_link_to 'Ajax forms', '5/4' %></li>
    <li><%= index_link_to 'Setup forms', '5/5' %></li>
  </ol>
  <h3><li>Stocktake</li></h3>
  <ol>
    <li><%= index_link_to 'Index file', '7/1' %></li>
  </ol>
  <h3><li>Render</li></h3>
  <ol>
    <li><%= index_link_to 'Get data', '8/1' %></li>
    <li><%= index_link_to 'HTML templates', '8/2' %></li>
    <li><%= index_link_to 'Render rooms', '8/3' %></li>
    <li><%= index_link_to 'Room links', '8/4' %></li>
    <li><%= index_link_to 'Render messages', '8/5' %></li>
    <li><%= index_link_to 'Time ago', '8/6' %></li>
  </ol>
  <h3><li>Update</li></h3>
  <ol>
    <li><%= index_link_to 'Render updates', '9/1' %></li>
    <li><%= index_link_to 'Form errors', '9/2' %></li>
    <li><%= index_link_to 'Improving the app', '9/3' %></li>
  </ol>
</ol>
<p>
  <%= link_to icon_text('Start: Browser inspector', 'fa-arrow-right'), workshop_path(page: '1/1'), class: 'btn btn-info pull-right' %>
</p>